### ISSUE TITLE
Support for different file path for scalastyle

### ISSUE THREAD

**Issue by mycaule** [buildo/linter-scalastyle#3]
I get errors for `/path/to/scalastyle` due to the spawn call.
https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

The location part of the path should be split before the call.
Adding scalastyle to the system `PATH` solves the problem.

**Comment by gabro** [comment]
Hi @mycaule, I'm not actively maintaining this project, but I'll review and merge a PR that fixes this. Thanks :)

**Comment by mycaule** [comment]
Don't need this.
